# Generated by Django 4.0.8 on 2024-04-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_quizscore_coursecompletionstatusperuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseCompletionStatusPerUser',
            new_name='CourseCompletionStatus',
        ),
    ]
