# Generated by Django 4.0.8 on 2024-04-12 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_rename_coursecompletionstatusperuser_coursecompletionstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseCompletionStatus',
            new_name='CourseCompletionStatusPerUser',
        ),
    ]
