# Generated by Django 4.0.8 on 2024-04-12 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_remove_customer_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userroleprivileges',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_privileges', to='exam.role'),
        ),
    ]
